# config/mode.yaml
# Polyglot Application Mode Configuration

# Application mode - determines how the app operates and connects
# Options: offline, local, cloud, bluetooth, mixed
mode: local

# Local mode configuration
local:
  # Use local models and storage only
  enabled: true
  # Local model providers to enable
  providers:
    - ollama
    - llamacpp
    - openai-compatible
  # Local storage settings
  storage:
    type: indexeddb
    backup_to_file: false
    auto_sync: false
  # API endpoints for local services
  endpoints:
    ollama: "http://localhost:11434"
    llamacpp: "http://localhost:8080"
    openai_compatible: "http://localhost:1234"

# Cloud mode configuration
cloud:
  enabled: false
  # Cloud providers to enable
  providers:
    - openai
    - anthropic
    - google
    - azure
  # Remote storage/sync settings
  storage:
    sync_enabled: false
    backend_url: ""
    auth_required: true
  # API configuration
  rate_limiting:
    enabled: true
    requests_per_minute: 60
  # Data privacy settings
  privacy:
    log_conversations: false
    encrypt_storage: true

# Bluetooth mode configuration (for device-to-device communication)
bluetooth:
  enabled: false
  # Bluetooth Low Energy settings
  ble:
    service_uuid: "12345678-1234-5678-9012-123456789abc"
    characteristics:
      chat_data: "87654321-4321-8765-2109-cba987654321"
      sync_status: "11111111-2222-3333-4444-555555555555"
  # Device discovery settings
  discovery:
    scan_duration: 30000 # milliseconds
    auto_connect: false
    trusted_devices: []

# Hybrid mode configuration (combines multiple modes)
hybrid:
  enabled: false
  # Primary mode for different operations
  primary_providers:
    chat: local
    storage: local
    sync: cloud
  # Fallback chain
  fallback_order:
    - local
    - cloud
  # Load balancing
  load_balancing:
    enabled: false
    strategy: round_robin # round_robin, least_latency, random

# Feature flags
features:
  # UI features
  conversation_export: true
  conversation_import: true
  dark_mode: true
  search_conversations: true

  # Advanced features
  model_switching: true
  multi_provider: true
  offline_mode: true
  background_sync: true

  # Experimental features
  voice_input: false
  real_time_collaboration: false
  plugin_system: false

# Performance settings
performance:
  # Memory management
  max_conversations_in_memory: 100
  conversation_cache_size: 50
  message_batch_size: 20

  # Network settings
  request_timeout: 30000 # milliseconds
  retry_attempts: 3
  concurrent_requests: 5

# Security settings
security:
  # API key encryption
  encrypt_api_keys: true
  api_key_storage: secure # secure, local, session

  # Content filtering
  content_filtering:
    enabled: false
    level: moderate # strict, moderate, permissive

  # CORS settings (for local development)
  cors:
    enabled: true
    allowed_origins: ["http://localhost:*", "https://localhost:*"]

# Development settings
development:
  debug_mode: false
  verbose_logging: false
  mock_responses: false
  # Development server settings
  dev_server:
    port: 8080
    hot_reload: true
    open_browser: true

# Version and compatibility
version: "1.0.0"
config_version: "1.0"
min_app_version: "1.0.0"

# Metadata
metadata:
  created_date: "2025-09-17"
  last_modified: "20245-09-17"
  description: "Polyglot application mode configuration"
  maintainer: "Polyglot Team"
