# config/mode.yaml
# Polyglut Application Mode Configuration

# Application mode - determines how the app operates and connects
# Options: standalone, local_network, cloud, hybrid
mode: standalone

# Standalone mode configuration (single device, no network required)
standalone:
  enabled: true
  # Core services
  services:
    # MCP server (bundled with app)
    mcp_server:
      enabled: true
      port: 9001
      auto_start: true
      bundled: true
    # Merge queue server (optional external service)
    merge_queue_server:
      enabled: false
      port: 4001
      auto_start: false
      required: false
  # Local model providers
  providers:
    - ollama
    - llamacpp
    - openai-compatible
  # Storage settings
  storage:
    type: indexeddb
    backup_to_file: false
  # API endpoints for local services
  endpoints:
    ollama: "http://localhost:11434"
    llamacpp: "http://localhost:8080"
    openai_compatible: "http://localhost:1234"
    mcp_server: "http://localhost:9001"
    merge_queue_server: "http://localhost:4001"

# Local network mode configuration (shared across LAN devices)
local_network:
  enabled: false
  # Core services
  services:
    mcp_server:
      enabled: true
      port: 9001
      auto_start: true
      bundled: true
    merge_queue_server:
      enabled: true
      port: 4001
      auto_start: false
      required: false
      # Network sharing settings
      shared_across_network: true
      discovery_enabled: true
  # Network discovery
  discovery:
    mdns_enabled: true
    broadcast_port: 8765
    service_name: "_polyglut._tcp"
  # Shared providers across network
  providers:
    - ollama
    - llamacpp
    - shared_models
  # Network storage settings
  storage:
    type: distributed
    sync_across_devices: true

# Cloud mode configuration
cloud:
  enabled: false
  # Core services (cloud doesn't need local services)
  services:
    mcp_server:
      enabled: false
    merge_queue_server:
      enabled: false
  # Cloud providers
  providers:
    - openai
    - anthropic
    - google
  # Remote storage/sync settings
  storage:
    sync_enabled: true
    backend_url: ""

# Hybrid mode configuration
hybrid:
  enabled: false
  # Core services
  services:
    mcp_server:
      enabled: true
      port: 9001
      auto_start: true
    merge_queue_server:
      enabled: true
      port: 4001
      auto_start: false
  # Primary mode for different operations
  primary_providers:
    chat: standalone
    storage: standalone
    sync: local_network
  # Fallback chain
  fallback_order:
    - standalone
    - local_network
    - cloud

# Service health checks
health_checks:
  enabled: true
  interval: 30000  # milliseconds
  services:
    mcp_server:
      endpoint: "/health"
      timeout: 5000
    merge_queue_server:
      endpoint: "/status"
      timeout: 5000

# Version and compatibility
version: "1.0.0"
config_version: "1.0"